# Generated by Django 6.0.1 on 2026-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0003_tag_alter_review_marks_numbercar_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='marks',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('3', '3'), ('1', '1')], default='5', max_length=100),
        ),
    ]
