# Generated by Django 6.0.1 on 2026-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0004_alter_review_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='marks',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('3', '3'), ('5', '5'), ('1', '1')], default='5', max_length=100),
        ),
    ]
