# Generated by Django 6.0.1 on 2026-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0005_alter_review_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='marks',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('1', '1'), ('2', '2'), ('4', '4')], default='5', max_length=100),
        ),
    ]
