# Generated by Django 6.0.1 on 2026-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Укажите язык программирования')),
                ('description', models.TextField(verbose_name='Укажите описание языка программирования')),
                ('image', models.ImageField(upload_to='proglang/', verbose_name='Загрузите изображение языка программирования')),
                ('create_date_lang', models.PositiveBigIntegerField(blank=True, verbose_name='Укажите год создания языка программирования')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
    ]
