# Generated by Django 6.0.1 on 2026-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
